config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :users do
    resources :favorites, only: %i[ create destroy ]
  end

  resource :session
  resources :passwords, param: :token

  get "up" => "rails/health#show", as: :rails_health_check

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "home#index"

  get "about" => "static_pages#about"
  get "imprint" => "static_pages#imprint"
  get "contact" => "static_pages#contact"
end

app/views/partials/_flash.html.erb
<div class="absolute right-4 top-28 md:top-36 z-50">
    <% if notice %>
        <div data-controller="flash" data-flash-target="notification" class="bg-[#3F3F3F] w-56 max-w-56 md:max-w-72 rounded px-2 py-1 my-1">
            <div class="flex justify-between items-center">
                <h5 class="text-white text-xl">Notification</h5>
                <button data-action="flash#toggle" class="text-white text-xl">x</button>
            </div>
            <p class="my-2 text-white overflow-clip"><%= notice %></p>
        </div>
    <% end %>

    <% if alert %>
        <div data-controller="flash" data-flash-target="notification" class="bg-[#3F3F3F] w-56 max-w-56 md:max-w-72 rounded px-2 py-1 my-1">
            <div class="flex justify-between items-center">
                <h5 class="text-white text-xl">Alert</h5>
                <button data-action="flash#toggle" class="text-white text-xl">x</button>
            </div>
            <p class="my-2 text-white overflow-clip"><%= alert %></p>
        </div>
    <% end %>
</div>

app/views/partials/_footer.html.erb
<footer class="bg-[#3F3F3F] fixed bottom-0 w-full h-12 flex items-center z-50">
    <ul class="w-full flex justify-evenly items-center">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Imprint", imprint_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
    </ul>
</footer>

app/views/partials/_header.html.erb
<header class="w-full bg-[#3F3F3F] h-28 md:h-32 flex items-center justify-between px-5 z-50">
    <%= link_to root_path do %>
        <img src="/icon.svg" alt="Logo" class="w-24 md:w-28">
    <% end %>

    <div data-controller="header--mobile" class="md:hidden">
    <button data-action="header--mobile#toggle" class="flex flex-col justify-around items-center w-14 aspect-square">
        <div class="w-full h-2 bg-[#D9D9D9] rounded-2xl"></div>
        <div class="w-full h-2 bg-[#D9D9D9] rounded-2xl"></div>
        <div class="w-full h-2 bg-[#D9D9D9] rounded-2xl"></div>
    </button>
    <nav data-header--mobile-target="navarea" class="hidden bg-[#3F3F3F] absolute left-0 top-28 w-full">
        <div class="w-full h-3 bg-[#393939]"></div>
        <ul class="text-white px-5 py-5 text-2xl">
        <li class="my-2"><%= link_to 'Homepage', root_path %></li>
        <li class="my-2"><%= link_to 'Ingredient List', ingredients_path %></li>
        <% if authenticated? %>
            <li class="my-2"><%= link_to "Profile (logged in as #{Current.user.username})", Current.user %></li>
            <li class="my-2"><%= button_to "Logout", session_path, method: :delete %></li>
        <% else %>
            <li class="my-2"><%= link_to 'Login', new_session_path %></li>
            <li class="my-2"><%= link_to 'Register', new_user_path %></li>
        <% end %>
        </ul>
    </nav>
    </div>

    <div class="hidden md:flex items-center">
    <ul class="mr-5 flex text-white text-xl">
        <li class="mx-2"><%= link_to "Homepage", root_path %></li>
        <li class="mx-2"><%= link_to "Ingredient List", ingredients_path %></li>
        <% if administrator? %>
            <li class="mx-2"><%= link_to "Users", users_path %></li>
        <% end %>
    </ul>
    <div data-controller="header--profile">
        <%= image_tag authenticated? ? "pfp.jpg" : "unauthenticated.jpg", class: "cursor-pointer h-20 aspect-square rounded-full border-black border-1", data: { action: "click->header--profile#toggle" }, alt: "Profile picture" %>
        <div data-header--profile-target="profilearea" class="hidden bg-white border-black border-2 absolute w-42 right-2 top-28 rounded-2xl px-2 py-1">
        <% if authenticated? %>
            <p class="text-2xl text-center mb-2"><%= Current.user.username %></p>
            <div class="flex flex-col">
            <%= link_to "Profile", Current.user, class: "text-xl" %>
            <%= button_to "Logout", session_path, method: :delete, class: "text-xl cursor-pointer" %>
            </div>
        <% else %>
            <div class="flex flex-col">
            <%= link_to "Login", new_session_path, class: "text-xl" %>
            <%= link_to "Register", new_user_path, class: "text-xl" %>
            </div>
        <% end %>
        </div>
    </div>
    </div>
</header>