config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :users do
    resources :favorites, only: %i[ create destroy ]
  end

  resource :session
  resources :passwords, param: :token

  get "up" => "rails/health#show", as: :rails_health_check

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "home#index"

  get "about" => "static_pages#about"
  get "imprint" => "static_pages#imprint"
  get "contact" => "static_pages#contact"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :favorites

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :description, length: { maximum: 1000 }
  validates :dosage, length: { maximum: 20 }
  validates :rating, presence: true

  enum :rating, { bad: 0, meh: 1, good: 2 }, validate: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  disallow_user_access except: %i[ index show ]
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    if params[:query]
      query = "%#{params[:query].downcase}%"
      @ingredients = Ingredient.where("LOWER(name) LIKE :query", query: query)
    else
      @ingredients = Ingredient.order("LOWER(name)")
    end
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy!

    respond_to do |format|
      format.html { redirect_to ingredients_path, status: :see_other, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.expect(ingredient: [ :name, :description, :dosage, :rating ])
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, class: "contents") do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul class="list-disc ml-6">
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ingredient.errors[:name].none?, "border-red-400 focus:outline-red-600": ingredient.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ingredient.errors[:description].none?, "border-red-400 focus:outline-red-600": ingredient.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :dosage %>
    <%= form.text_field :dosage, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ingredient.errors[:dosage].none?, "border-red-400 focus:outline-red-600": ingredient.errors[:dosage].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :rating %>
    <%=  form.select :rating, Ingredient.ratings.keys.map { |r| [r.humanize, r] } %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= ingredient.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= ingredient.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Dosage:</strong>
    <%= ingredient.dosage %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Rating:</strong>
    <%= ingredient.rating %>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="w-full flex flex-col items-center">
    <h2 class="text-center text-3xl">Edit <%= @ingredient.name %></h2>

    <%= form_with model: @ingredient, class: "w-full flex flex-col items-center" do |form| %>

        <% if @ingredient.errors.any? %>
            <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 max-w-100">
                <h2><%= @ingredient.errors.count %> prevented updating this ingredient:</h2>

                <ul>
                    <% @ingredient.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="mt-20 w-full md:w-1/2 lg:w-1/3 flex flex-col items-center">
            <%= form.text_field :name, placeholder: "Name", class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
            <%= form.text_area :description, placeholder: "Description", class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
            <%= form.text_field :dosage,  placeholder: "Dosage", class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
            <%=  form.select :rating, Ingredient.ratings.keys.map { |r| [r.humanize, r] } %>
        </div>

        <div class="w-full mt-24 flex items-center justify-around">
            <%= form.submit "Update", class: "w-34 h-14 bg-[#0088DD] hover:bg-[#0088FF] rounded-2xl text-2xl text-white flex justify-center items-center" %>
        </div>
    <% end %>
</div>

app/views/ingredients/index.html.erb
<div class="w-full flex flex-col items-center">

    <div class="flex w-full justify-center items-center">
      <h2 class="text-center text-3xl">Ingredients</h2>
      <% if administrator? %>
        <%= link_to "Add", new_ingredient_path, class: "ml-5 w-20 h-10 bg-[#0088DD] hover:bg-[#0088FF] rounded-2xl text-2xl text-white flex justify-center items-center" %>
      <% end %>
    </div>

    <div class="mt-8 bg-gray-200 h-24 w-100 px-4 py-1 rounded-3xl">
        <span class="text-xl">Search for ingredients</span>

        <%= form_with url: ingredients_path, method: :get, data: { turbo_frame: "ingredients" }, class: "mt-5 flex items-center justify-around" do |form| %>
            <%= form.text_field :query, placeholder: "Name....", class: "bg-gray-300 w-full h-[2em] rounded-4xl px-2" %>
            <button type="submit">
                <%= image_tag "icons/search.svg", class: "h-[1.5em] mx-5" %>
            </button>
        <% end %>
    </div>

    <%= turbo_frame_tag "ingredients", class: "mt-12 w-full" do %>
        <div class="relative flex flex-col w-full h-full text-gray-700 z-30">
          <table class="max-w-full text-left table-auto">
            <thead>
              <tr>
                <th class="p-4 border-b text-gray-600 text-sm">Name</th>
                <th class="p-4 border-b text-gray-600 text-sm">Dosage</th>
                <th class="p-4 border-b text-gray-600 text-sm">Rating</th>
                <th class="p-4 border-b text-gray-600 text-sm">
                </th>
              </tr>
            </thead>
            <tbody>
              <% @ingredients.each do |ingredient| %>
                <tr>
                  <td class="p-4 border-b w-2/5 max-w-xs whitespace-normal break-words"><%= ingredient.name %></td>
                  <td class="p-4 border-b w-1/5"><%= ingredient.dosage %></td>
                  <td class="p-4 border-b w-1/5"><%= ingredient.rating.humanize %></td>
                  <td class="p-4 border-b w-1/5"><%= link_to "View", ingredient, target: "_top" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
</div>

app/views/ingredients/new.html.erb
<% content_for :title, "New ingredient" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to "Back to ingredients", ingredients_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/ingredients/show.html.erb
<div class="w-full">
  <div class="flex items-center">
    <h1 class="font-bold text-4xl">Ingredient <%= @ingredient.name %></h1>
    <%# data: { turbo_frame: "favorite" } %>
    <%#= turbo_frame_tag "favorite" do %>
      <% if authenticated? %>
        <% if Current.user.favorite_ingredients.include? @ingredient %>
          <%= form_with model: [Current.user, Current.user.favorites.find_by(ingredient_id: @ingredient.id)], method: :delete do |form| %>
            <button type="submit">
              <%= image_tag "icons/star_filled.svg", class: "ml-5 h-5 w-5 cursor-pointer" %>
            </button>
          <% end %>
        <% else %>
          <%= form_with model: [Current.user, Favorite.new] do |form| %>
            <%= form.hidden_field :ingredient_id, value: @ingredient.id %>
            <button type="submit">
              <%= image_tag "icons/star_empty.svg", class: "ml-5 h-5 w-5 cursor-pointer" %>
            </button>
          <% end %>
        <% end %>
      <% end %>
    <%# end %>
  </div>

  <div class="mt-20 text-xl w-full flex flex-col items-center">
    <p><%= @ingredient.description %></p>
  
    <p><strong>Dosage:</strong> <%= @ingredient.dosage %></p>
    <p><strong>Rating:</strong> <%= @ingredient.rating.humanize %></p>
  </div>

  <% if administrator? %>
    <div class="w-full mt-24 flex items-center justify-around">
        <%= link_to "Edit", edit_ingredient_path(@ingredient), class: "w-34 h-14 bg-[#0088DD] hover:bg-[#0088FF] rounded-2xl text-2xl text-white flex justify-center items-center" %>
        <%= button_to "Delete", @ingredient, method: :delete, data: { turbo_confirm: "Are you sure you want to delete #{@ingredient.name}?" }, class: "w-34 h-14 bg-red-600 hover:bg-red-700 rounded-2xl text-2xl text-white cursor-pointer" %>
    </div>
  <% end %>
</div>